### ISSUE TITLE
Download all OSrPRE data

### ISSUE THREAD

**Issue by georgiamoon** [PREreview/rapid-prereview#117]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%24100%20Funded-%2300A156.svg" />](https://issuehunt.io/r/PREreview/rapid-prereview/issues/117)

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $100.00)

- [<img src='https://avatars1.githubusercontent.com/u/39268982?v=4' alt='prereview' width=24 height=24> prereview](https://issuehunt.io/u/prereview) ($100.00)

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/PREreview/rapid-prereview/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by brymut** [comment]
Hi @georgiamoon, I would like to take a shot at this. May I please get a little more info of what we'd like done for this. Will we be looking to get all of the data in a specific format? And how would this all be accessed by users in the API and UI?

**Comment by harumhelmy** [comment]
Hi @brymut! A colleague and I actually started working on a script in a separate repo that would end up meeting the needs of this issue. Sorry for the bad communication here. We're working on adding more issues and attaching them to bounties as the project continues to evolve — hope you'll continue to be interested in contributing! Thanks for hollering!

**Comment by brymut** [comment]
No prob @harumhelmy , thanks for clarifying.
