### ISSUE TITLE
Download all data data related to a search, e.g. "COVID19"

### ISSUE THREAD

**Issue by georgiamoon** [PREreview/rapid-prereview#118]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%24100%20Funded-%2300A156.svg" />](https://issuehunt.io/r/PREreview/rapid-prereview/issues/118)

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $100.00)

- [<img src='https://avatars1.githubusercontent.com/u/39268982?v=4' alt='prereview' width=24 height=24> prereview](https://issuehunt.io/u/prereview) ($100.00)

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/PREreview/rapid-prereview/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by ChaituVR** [comment]
Can i know more about this? should display a download button in search page that downloads all pdfs or all data as csv?

**Comment by georgiamoon** [comment]
hi @ChaituVR ! Yes — sorry for not putting more info here, but what I was thinking was basically export all meta-data as a summary csv and maybe a json output that's easy for someone to work with. I could imagine the csv looking like:

`doi, requests_count, reviews_count,requests_userids,reviews_userids, aggregated stats from the review form`

and potentially the json would have an object that listed the individual review data?

If you have suggestions based on looking at the API, or if @jheretic @harumhelmy want to weigh in as they've been doing some API work that'd be great too!

**Comment by harumhelmy** [comment]
Hi @ChaituVR @georgiamoon! We're almost done working on a script that would meet the behavior desired by this issue, so we're thinking we're going to close this one. Sorry about not updating this issue sooner, that was our bad :/
