### ISSUE TITLE
Mozilla Sprint Series

### ISSUE THREAD

**Issue by murkatr** [PREreview/rapid-prereview#120]
Mozilla has funded PREreview to hold a Mozilla Sprint Series before the end of August (at the latest).

Sprint 1: internal 
Sprint 2: invite Mozilla and eLIFE and others

See [folder](https://drive.google.com/drive/folders/1N3M4xZiF2vni0v-rQk8AU_u7IW7uiC8q) and [overview](https://docs.google.com/document/d/1Gdzo3_suTS9pnEaR208YHX8AvOTGCa0sUxAIcYf8QX4/edit) for more information.

**Comment by jheretic** [comment]
Replaced w/ the Mozilla Sprint Series milestone.
