### ISSUE TITLE
The two text field questions are showing up in the middle of the question form

### ISSUE THREAD

**Issue by georgiamoon** [PREreview/rapid-prereview#122]
Reported by @dasaderi after the June 15, 2020 deployment
<img width="1429" alt="Screen Shot 2020-06-16 at 2 25 41 PM" src="https://user-images.githubusercontent.com/941210/84847553-6ac52080-b01f-11ea-9ab8-1e106e3d268d.png">

**Comment by harumhelmy** [comment]
After [investigating git blame](https://github.com/PREreview/rapid-prereview/commit/3a16fed1afcc83625e797c41a29129f945c21062), it looks like those two text-field questions were moved there back in April by another developer. It's very easy to move it back, but just wanted to bring this into attention, in case the text-fields were moved to where they are now for another reason.
