### ISSUE TITLE
Getting rid of the structured form "not in context"

### ISSUE THREAD

**Issue by dasaderi** [PREreview/rapid-prereview#134]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%24100%20Funded-%2300A156.svg" />](https://issuehunt.io/r/PREreview/rapid-prereview/issues/134)

I find it confusing to have the visualization of the form "not in context". I would like to suggest a workflow that connects directly the action of "Add a review" to the split screen view "in context" of the form and the preprint.

So basically after a user clicks on Add a review after pasting the DOI instead of going here:

<img width="1432" alt="Screen Shot 2020-07-03 at 3 55 21 PM" src="https://user-images.githubusercontent.com/13750121/86500434-d4df0480-bd45-11ea-9663-2d58c8f97cf5.png">

we go directly to the split screen view:

<img width="1440" alt="Screen Shot 2020-07-03 at 3 57 34 PM" src="https://user-images.githubusercontent.com/13750121/86500450-f04a0f80-bd45-11ea-9133-4c1ba9011fc7.png">

@majohansson @georgiamoon @carijyao what do you think?

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $100.00)

- [<img src='https://avatars1.githubusercontent.com/u/39268982?v=4' alt='prereview' width=24 height=24> prereview](https://issuehunt.io/u/prereview) ($100.00)

### Submitted pull Requests
- [#141 ux: Getting rid of the structured form "not in context"](https://issuehunt.io/r/PREreview/rapid-prereview/pull/141)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/PREreview/rapid-prereview/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by georgiamoon** [comment]
I agree! Maybe we could tag this for the sprint as well @jheretic @rudietuesdays @harumhelmy

**Comment by georgiamoon** [comment]
To make this change the UI flow should be:

- Click "Add a review | Request a review"
- Enter the DOI
- if the user clicks "Add Review"
    - Rather than seeing just the form, take the user to the view of the PDF view with the form next to it, or overlayed (depending on screen size)
- If the user clicks "Request Reviews"
    - Remove the "View in Context" option from the box, and just have "Go Back" and "Submit"
