### ISSUE TITLE
Complete dashboard front end

### ISSUE THREAD

**Issue by rudietuesdays** [PREreview/rapid-prereview#135]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%24100%20Funded-%2300A156.svg" />](https://issuehunt.io/r/PREreview/rapid-prereview/issues/135)

Build a semi-dynamic front end for the dashboard, following the wireframe [here](https://github.com/PREreview/rapid-prereview/issues/80#issuecomment-652801118) including:

- [x] Reuse components such as search bar that have already been built
- [x] Ensure dynamic components have proper functions available to work correctly
- [x] Create rest of wireframe (statically) using accessibility best practices
- [x] Follow general style structure to match rest of site

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $100.00)

- [<img src='https://avatars1.githubusercontent.com/u/39268982?v=4' alt='prereview' width=24 height=24> prereview](https://issuehunt.io/u/prereview) ($100.00)

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/PREreview/rapid-prereview/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by TheGuardianWolf** [comment]
I'm looking to start work on this issue, what's the relation between this one and #80? Does one need to be completed first?

**Comment by harumhelmy** [comment]
Hey there @TheGuardianWolf sorry for the delay in responding -- this issue is actually fixed for now. Please take a look at other issues you might want to help with and feel free to tag me with any questions :)
