### ISSUE TITLE
Create a RSS Export

### ISSUE THREAD

**Issue by murkatr** [PREreview/rapid-prereview#137]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%24100%20Funded-%2300A156.svg" />](https://issuehunt.io/r/PREreview/rapid-prereview/issues/137)

We want to provide an RSS feed for partners to import.

They specifically need:
preprint DOI, review title, date, reviewer author name, link to OSrPRE

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $100.00)

- [<img src='https://avatars1.githubusercontent.com/u/39268982?v=4' alt='prereview' width=24 height=24> prereview](https://issuehunt.io/u/prereview) ($100.00)

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/PREreview/rapid-prereview/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by willianveiga** [comment]
@murkatr, I've been trying to fix this issue but I'm not sure how to get all the data.

Considering the RSS specification, what should I place in the title element? What about the description?

I appreciate if you can provide more technical details.

Thanks.

**Comment by jheretic** [comment]
Hi @willianveiga, that's a good question about the title and description fields. To give some context, this was floated as a possibility specifically for BioArxiv, who were basically willing even to scrape a static page for the content, as a more structured solution for them to keep track of new reviews without having to make a large number of API calls on their page load. Given that, I think there's a large amount of flexibility in how it's structured. This could even be a separate standalone script for generating an RSS feed from the JSON data, as opposed to a proper part of the API. The API documentation for OSrPRE is at https://outbreaksci.prereview.org/api, and here are some examples of how to access the data for preprints:
```
curl 'https://outbreaksci.prereview.org/api/preprint?q=*:*&include_docs=true'
```
and reviews:
```
curl 'https://outbreaksci.prereview.org/api/action?q=*:*&include_docs=true'
```

Would be down to chat more about structure!

**Comment by willianveiga** [comment]
With your help @jheretic, I've created a draft PR.

I appreciate if you could give me a feedback to continue working on it.

Thank you.

**Comment by spiritbroski** [comment]
still not done yet?

**Comment by jheretic** [comment]
Hi @spiritbro1, thanks for the note that we should probably close this out. We ended up implementing this export as a separate script which you can find here: https://github.com/PREreview/PREreview-feed, and the new platform that merges the features and data from both https://prereview.org and this project is being developed here: https://github.com/prereview/prereview and will include a data export in RSS and other standardized formats built-in to the API.
