### ISSUE TITLE
Add extension banner to the hompage

### ISSUE THREAD

**Issue by dasaderi** [PREreview/rapid-prereview#164]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%24100%20Funded-%2300A156.svg" />](https://issuehunt.io/r/PREreview/rapid-prereview/issues/164)

I think it would be useful to point out that a user does not have the extension installed. I saw this on [PubPeer](https://pubpeer.com/), and quite like that idea. 

I suggest adding a message such as "You have not yet installed the Outbreak Science Rapid PREreivew browser extension to enable requesting, adding and/or reading rapid reviews on other websites. Install it [here](https://outbreaksci.prereview.org/extension)!"

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $100.00)

- [<img src='https://avatars1.githubusercontent.com/u/39268982?v=4' alt='prereview' width=24 height=24> prereview](https://issuehunt.io/u/prereview) ($100.00)

### Submitted pull Requests
- [#168 Add extension banner to the hompage](https://issuehunt.io/r/PREreview/rapid-prereview/pull/168)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/PREreview/rapid-prereview/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by ChaituVR** [comment]
I've started working on this, will raise PR soon

**Comment by ChaituVR** [comment]
@dasaderi this issue will auto-close on merge of #168 until then please re-open

**Comment by dasaderi** [comment]
Sorry about that @ChaituVR. Re-opened.
