### ISSUE TITLE
In Chrome but not in Firefox problem loading the pdf of a new preprint 

### ISSUE THREAD

**Issue by dasaderi** [PREreview/rapid-prereview#167]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%24100%20Funded-%2300A156.svg" />](https://issuehunt.io/r/PREreview/rapid-prereview/issues/167)

In Chrome but not in Firefox the pdf of a new preprint that has not already being reviewed or requested for review on OSrPRE does not load. The problem is not there at all in Firefox. In order to get it to load, one has to first request it for review, which should not be the way that is done. 

<img width="1425" alt="Screen Shot 2020-08-13 at 12 54 04 PM" src="https://user-images.githubusercontent.com/13750121/90180780-52922900-dd64-11ea-87b4-4a4d05158740.png">

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $100.00)

- [<img src='https://avatars1.githubusercontent.com/u/39268982?v=4' alt='prereview' width=24 height=24> prereview](https://issuehunt.io/u/prereview) ($100.00)

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/PREreview/rapid-prereview/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by leonardosfl** [comment]
I think it's the same issue I pointed here: https://github.com/PREreview/rapid-prereview/pull/160
