### ISSUE TITLE
Update About page with new content

### ISSUE THREAD

**Issue by dasaderi** [PREreview/rapid-prereview#170]
I will work on updating a google doc with this content as I can't directly change the page. 

Things to update (this list is a work in progress):
- [ ] Add info about OASPA
- [ ] Add call to action re COVID-19 review
- [ ] Add info about how to contribute/give feedback including the code and link to the issues for the sprint
- [ ] Add Mozilla and Sloan to list of funders.

**Comment by murkatr** [comment]
This is now #249 in DreamTeam repo
