### ISSUE TITLE
Get number of reviews and requests updated at the top of the search 

### ISSUE THREAD

**Issue by dasaderi** [PREreview/rapid-prereview#172]
I keep getting questions about how many requests for reviews and reviews of COVID-19 preprints are in the website and realize we don't have a quick way of assessing that — unless I'm missing it. Perhaps showing numbers somewhere at the top of the search that updates with the filters that are clicked would be helpful? Both in the homepage and the dashboard? I noticed numbers show up in light grey near the filters "with reported data" and "with reported code". Maybe something like that would work? 

@georgiamoon @harumhelmy @carijyao thoughts?

**Comment by georgiamoon** [comment]
Yeah — I think that's a good idea, some sort of summary stats on the dashboard page. 

@carijyao and I chatted about this today and started working on a sketch.
