### ISSUE TITLE
Add checkbox to agree to CoC when first log in

### ISSUE THREAD

**Issue by dasaderi** [PREreview/rapid-prereview#38]
If possible to do before December 3rd.

**Comment by sballesteros** [comment]
@halmos and I spent some time to discuss that and we think that the best approach is to render a modal with the CoC to the user the first time he/she logs in. Flow would be:
1. user visit /login
2. user is redirected to ORCID to enter credentials
3. user is redirected from ORCID back to rapid (/setting page) and at that point we render the modal.

The modal would be titled smtg like: "Welcome, to continue you need to first accept the CoC" and will block the user to do anything until a "I agree" button is clicked.
