### ISSUE TITLE
Modify Rapid CoC prior to launch

### ISSUE THREAD

**Issue by dasaderi** [PREreview/rapid-prereview#39]
@dasaderi to modify [here](https://github.com/PREreview/rapid-prereview/blob/master/src/components/code-of-conduct.js) in a new coc branch and label changes with "TODO @sballesteros".

- [x] Specify that content will be moderated after it's posted. Community members will be able to flag potential violations and admins will evaluate and decide if the content needs to be removed and/or the user needs to be blocked.

- [ ] Specify that the site is for outbreak-related content only.

**Comment by dasaderi** [comment]
I made a coc-edits branch and edited the COC there. @sballesteros is there a way to visualize it or test it before joining to master and deploying it?

**Comment by sballesteros** [comment]
cool thanks, yes running the website locally as per the README will let you visualise the CoC at http://127.0.0.1:3000/code-of-conduct 
Once you are happy with it, you can send a pull request and i will merge and redeploy.

**Comment by sballesteros** [comment]
Also ping @halmost if you want some style adjustment for the bullet points etc.

**Comment by dasaderi** [comment]
Thank you. I think we need @majohansson to take a look at it.

**Comment by majohansson** [comment]
@dasaderi I looked at your edits here: https://github.com/PREreview/rapid-prereview/blob/coc-edits/src/components/code-of-conduct.js

It looks good. My concern on the COI is that I am not sure how a reviewer will report that? We don't have a specific mechanism for that other than using the text that is already there. Is a better policy to say "Do not review a paper if you have a COI"?
