### ISSUE TITLE
data for chrome and firefox webstores

### ISSUE THREAD

**Issue by sballesteros** [PREreview/rapid-prereview#43]
- [x] icon (@halmos) must respect the exact width and height. See screenshot below and https://developer.chrome.com/webstore/images#icons
<img width="1213" alt="Screen Shot 2019-12-01 at 11 56 44 AM" src="https://user-images.githubusercontent.com/1141327/69919456-ccca8980-1431-11ea-8d8a-f0a9da0df144.png">

- [x] detailed description (@dasaderi  or @majohansson ) see screenshot below for instructions
<img width="1162" alt="Screen Shot 2019-12-01 at 11 56 37 AM" src="https://user-images.githubusercontent.com/1141327/69919457-ccca8980-1431-11ea-9ae3-7eef454983c4.png">

- [x] provide info to chrome and firefox stores and resubmit the application (@sballesteros)

-----

### Chrome

> Your item did not comply with the following section of our [Program Policies](https://developer.chrome.com/webstore/program_policies):
> "Spam and Placement in the Store"
> Item has a blank description field, or missing icons or screenshots, and appears to be suspicious.

### Firefox

> Jack Thompson wrote:
> Please expand this add-on listing. Describe the purpose and features/interface changes/actions of this add-on in more detail and/or have images demonstrating the features. For suggestions on how to create a better listing see https://developer.mozilla.org/Add-ons/Listing .
> Thank you.

**Comment by dasaderi** [comment]
Detailed description – I have no idea if this is okay:

**Outbreak Science Rapid PREreview** is an open science project born by the collaboration between [PREreview](https://v2.prereview.org) and [Outbreak Science](https://outbreakscience.org). This project focuses on building infrastructure for all researchers working in the field of infectious diseases to read, provide, and request feedback on emerging scientific literature published as preprints. 

Preprints are complete scientific manuscripts made available rapidly and freely online before editorial-organized peer review. They provide an opportunity for the scientific community to come together and give feedback to the authors, helping make the science better. 

Researchers with an ORCID iD can join the Outbreak Science Rapid PREreview community at outbreaksci.prereview.org and have the option to install this extension on their browser. This will allow them to easily read, provide, or solicit feedback on an outbreak-related preprint. A _rapid review_ is a review composed by a few, short multiple choice questions and two optional open-ended questions. 

For questions please visit outbreaksci.prereview.org and/or email us at outbreaksci@prereview.org.

**Comment by majohansson** [comment]
Made some light edits to the last paragraph. Also, I think anyone can install the browser extension, no? You only need to register to create reviews or requests, correct? Anyone should be able to install the extension to look at reviews, right?

**Comment by dasaderi** [comment]
Yeah, you are right, @majohansson.

**Comment by dasaderi** [comment]
I made some changes to the language to try reflecting that difference. Please let me know if it makes sense.

**Comment by sballesteros** [comment]
@majohansson  if you have 2 min can you provide a final go on that so that i can go ahead and update the submission ?

**Comment by majohansson** [comment]
I just updated again. Nothing controversial. @sballesteros please read through it again for typos and such. If good to you, go ahead and update. Thanks!
