### ISSUE TITLE
Delete a rapid review (not a CoC violation)

### ISSUE THREAD

**Issue by dasaderi** [PREreview/rapid-prereview#48]
Likely we will have to deal with users who submitted the review as a mistake. We as admin need a way to delete content that is not then labled as CoC violation. 

@sballesteros does this require development separate from what we already have?

**Comment by sballesteros** [comment]
Right now this can be done in 2 steps:
1. admin report the review (as a normal user would do)and specify a report reason
2. from the moderation panel admin moderate the review and specify the moderation reason

**Comment by dasaderi** [comment]
So deleting content is not automatically recorded as violation of CoC in the database?

**Comment by sballesteros** [comment]
No we record a `moderationReason`. The value is currently plain text so could be anything. We could introduce discrete options if you prefer.

**Comment by sballesteros** [comment]
Closing in favor of #59
