### ISSUE TITLE
Admin notification of a new Rapid Review

### ISSUE THREAD

**Issue by dasaderi** [PREreview/rapid-prereview#50]
It would be very useful for admins to get a notification of a new review. I'd be happy with an email sent to outbreaksci@prereview.org. 

This is both because we can go and moderate, and also because we can share on social media. Also see Issue #49.

@majohansson, what do you think?

**Comment by majohansson** [comment]
@dasaderi I can definitely see use in the short run. Long run it could be a pain in ***. If development is easy, and option might be a separate account so that it will be easier for us to filter?

**Comment by sballesteros** [comment]
https://docs.microsoft.com/en-us/azure/store-sendgrid-nodejs-how-to-send-email seems to be the simplest way to get transactional email on Azure.
