### ISSUE TITLE
Admin access to number of total reviews and requests 

### ISSUE THREAD

**Issue by dasaderi** [PREreview/rapid-prereview#53]
@sballesteros is there a way (doesn't need to be pretty) that admins can quickly see how many reviews and requests are at any point in time? It would be very useful for us to have easy access to those numbers.

**Comment by sballesteros** [comment]
Yes we have several CouchDB views giving us access to statistics.
if you login to Cloudant and visit: `/rapid-prereview-docs/_design/ddoc-docs/_view/byType?group_level=1` you will see some JSON response giving you a breakdown of the counts per types e.g:

```js
{
  rows: [
    { key: 'AnonymousReviewerRole', value: 6 },
    { key: 'PublicReviewerRole', value: 6 },
    { key: 'RapidPREreviewAction', value: 4 },
    { key: 'RequestForRapidPREreviewAction', value: 9 }
  ]
}
```

**Comment by sballesteros** [comment]
Ok to close?

**Comment by sballesteros** [comment]
This is now documented in https://github.com/prereview/rapid-prereview/#usage-stats
