### ISSUE TITLE
If a review is already in the system don't ask for DOI/arXiv profile

### ISSUE THREAD

**Issue by dasaderi** [PREreview/rapid-prereview#58]
@sballesteros we noticed that even when a preprint is already on the platform, if a user clicks on Add review, it will prompt them to add DOI/arXiv ID. Is this done on purpose?

**Comment by sballesteros** [comment]
sorry not sure i follow. 
Unless we have a regression or a bug:

Clicking on:
<img width="344" alt="Screen Shot 2019-12-12 at 10 56 35 AM" src="https://user-images.githubusercontent.com/1141327/70740667-7cbfb280-1cce-11ea-8bfd-d37bcb8fda49.png">

Always ask you for a DOI or ArxivId, if you enter one that's already in the system it will do the right thing that is:
- prevent you to add a request or a review if you have already done it 

Clicking on:
<img width="975" alt="Screen Shot 2019-12-12 at 10 57 55 AM" src="https://user-images.githubusercontent.com/1141327/70740560-44b86f80-1cce-11ea-8290-cd6978c7f52e.png">
Will open the same form _but_ with the DOI / ArxivId already prepropulated to the value of that preprint. If you have already written a request or a review for that preprint, clicking on that button will take you straight to the part that you haven't done (so if you did write a request but no review, you will get to the review form directly).

If things don't work like that there is a bug somewhere but I couldn't find any issues there on the latest code.

**Comment by dasaderi** [comment]
@sballesteros, yes your are right. For some reasons @georgiamoon and I thought it asked you to input DOI again. Sorry about that.

But I still find it confusing that for not-first time user that is not logged in, after prompting them to log in as a consequence of clicking the pill button under a pre-logged preprints, it brings you to the profile and not back to the action.

**Comment by sballesteros** [comment]
Ok thanks, I see, right now when you start from the homepage (and the the dedicated preprint page) _and_ your profile is incomplete we redirect you to the profile settings to try to get you to fill your profile info _before_ writing your review, but i agree that it's confusing so will remove it and close that issue.

**Comment by sballesteros** [comment]
Closing as remaining work is in https://github.com/PREreview/rapid-prereview/issues/45
