### ISSUE TITLE
Code of Conduct violation flagging

### ISSUE THREAD

**Issue by dasaderi** [PREreview/rapid-prereview#59]
I was thinking about this as I was writing the blog. Right now users can only flag violation of CoC of reviews that have open-ended text, right? But another way to violate the CoC is if an author of the preprint self evaluates their work, and that can be limited to the yes/no questions.

@sballesteros is it possible to have the flagging for violation available on any review?

**Comment by sballesteros** [comment]
We will generalize the UI to accommodate that use case.
