### ISSUE TITLE
Add About page 

### ISSUE THREAD

**Issue by dasaderi** [PREreview/rapid-prereview#61]
@halmos, as I mentioned in our last call, it would be very useful to just have one About page. We can have the content of the splash landing page, add a bit more about PRE and OS, contact info and funder statement. 
@sballesteros is this a lot of work? 
Happy to manage content via GitHub pages or, if it's too much, just have content editable in CSS (like CoC). A bit more complicated for us but easier for you. But we need something to acknowledge funders and teams.

**Comment by halmos** [comment]
This is definitely doable, but the approach depends a little bit on timeframe. If you need it before January then a hardwired React component is most feasible. However, once we have the static content CMS ready, it would be easy enough to host the about page on whatever system we land on (e.g. ghost).

**Comment by dasaderi** [comment]
@halmos @majohansson Here's the suggested text for About page. If possible I'd add the WT logo at the bottom near funding. 

## Project
**Outbreak Science Rapid PREreview** for the rapid review of outbreak-related preprints.
This open project is funded by the Wellcome Trust as a collaboration between Outbreak Science and PREreview.

**[Outbreak Science](https://outbreakscience.org/)** is a non-profit organization aiming to advance the science of outbreak response. Outbreak Science supports early and open dissemination of data, code, and research.

**[PREreview](https://v2.prereview.org)** is an open project fiscally sponsored by the non-profit organization Code for Science & Society. PREreview's mission is to increase diversity in the
scholarly peer review process by empowering all researchers to engage with preprint reviews.

## Team

### Leadership
Michael Johansson, Co-Founder, Director, Outbreak Science
Daniela Saderi, Co-Founder, Director, PREreview
Samantha Hindle, Co-Founder, Leadership Team PREreview
Monica Granados, Leadership Team PREreview

### Development team
Sebastien Ballesteros
Erik Wysocan

## Contacts
Email: outbreaksci@prereview.org
Twitter: [@outbreaksci](https://twitter.com/outbreaksci), [@PREreview_](https://twitter.com/PREreview_), #OSrPRE
GitHub: [https://github.com/PREreview/rapid-prereview](https://github.com/PREreview/rapid-prereview)

## Funding
[Wellcome Trust Open Research Fund](https://wellcome.ac.uk/funding/schemes/open-research-fund) 2018-2019

**Comment by majohansson** [comment]
@dasaderi Looks good. I made some minor text edits, which you can take or leave. Also, I think this might be a good place to re-state the 3 things you can do here:

1. Find rapid reviews of existing preprints.
2. Request reviews of preprints (your own, or preprints you are interested in).
3. Review preprints.

Up to you if you want to add though.

**Comment by dasaderi** [comment]
Great. Ready to be uploaded then. :)

**Comment by halmos** [comment]
This text was added in commit https://github.com/PREreview/rapid-prereview/commit/9f0ac3394302208956d882612ecca14986fa1ee8
