### ISSUE TITLE
Add link to the source code on the AMO and CWS pages

### ISSUE THREAD

**Issue by Vinnl** [PREreview/rapid-prereview#62]
https://addons.mozilla.org/en-GB/firefox/addon/outbreaksci-rapid-prereview/ says the extension is licensed under the MIT license, but there's no link to the source code anywhere, as far as I could find. https://chrome.google.com/webstore/detail/outbreak-science-rapid-pr/llglocdbioijhhfloamebnagdchmmabd doesn't specify a license nor link to the source code. Linking to this GitHub might be conducive to attracting contributors :)

**Comment by sballesteros** [comment]
Thanks! just added it to the descriptions.
