### ISSUE TITLE
Re-use existing libraries for detecting DOIs

### ISSUE THREAD

**Issue by Vinnl** [PREreview/rapid-prereview#63]
There's a lot of custom code in https://github.com/PREreview/rapid-prereview/blob/master/src/utils/scholar.js to detect DOI's in a page. I just thought I'd mention the existence of [get-dois](https://www.npmjs.com/package/get-dois), which supports all of the tags recognised by Google Scholar (and a few others), has full test coverage, and is shared with other projects. You might want to consider using that for non-arXiv preprint servers.

(But of course, feel free to close this issue if the current approach works just fine.)

**Comment by sballesteros** [comment]
Thanks, I added a note to scholar.js.

Most of the code in scholar.js is used to parse other metadata than the DOI. The DOI part itself is a few lines of code and mostly relies on https://github.com/regexhq/doi-regex (maybe `get-dois` could re-use that small module ?)

For the other metadata (date published etc.) we realized that we sometime need to interpret tags differently based on the preprint servers (see the special cases for bioRxiv and medRxiv for instance).

As a result for now we like having all the logic handling the `<head>` metadata as explicit as possible to be able to easily iterate on how we best approach the special cases.
