### ISSUE TITLE
Submit button should be referenced to the same storybook item across places

### ISSUE THREAD

**Issue by dasaderi** [PREreview/rapid-prereview#66]
Many users did not see the Submit button when in white. It looks like in some case Submit is in red in others it's in white similar to "Add review" and "Add request" button. 
@halmos can we make it consistently red to make it more obvious?

**Comment by georgiamoon** [comment]
To be clear: this is our guess about what's happening here, but the submit button in the shell is different than the submit button in the "Add Entry" overlay, and they should be consistent.

**Comment by halmos** [comment]
i went ahead made these red "primary" style buttons. i also added more space at the bottom to increase chance that user will scroll the controls into view.

**Comment by dasaderi** [comment]
Wonderful! Thank you, Erik!
