### ISSUE TITLE
allow to add reviews or requests for preprint before the DOI has been registered

### ISSUE THREAD

**Issue by sballesteros** [PREreview/rapid-prereview#73]
We get the metadata from the HTML of the preprint => we know everything we need _before_ the DOI is registered. This works well with the extension where we don't need to lookup the DOI at all.
However, server side we revalidate the metadata. To do so we rely on the DOI to get the URL of the HTML... That create issues as there can be cases where we do have all the metadata (from the HTML) but the server then tries to refetch them by resolving the DOI to the HTML URL. That last step doesn't work for recent entries as DOI provider sometimes lag a bit.

Solution: have the extension also send the URL of the preprint HTML and use that instead of the DOI when we can't resolve the DOI.

**Comment by majohansson** [comment]
@sballesteros That sounds like a good solution. Is there a potentially that could cause any issues for when preprints get updated? When they are updated on a preprint server, the server url may change (e.g. adds 'v2'), but the DOI is maintained (I think?) and directs to the updated version? Not at all sure if this could cause problems.
