### ISSUE TITLE
A topic/tag dashboard view for folks to understand information within a tag/topic

### ISSUE THREAD

**Issue by dasaderi** [PREreview/rapid-prereview#80]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%240%20Funded-%2300A156.svg" />](https://issuehunt.io/r/PREreview/rapid-prereview/issues/80)

Not specific to review content but a tool to help choose the preprint to review among a given topic:

e.g. a COVID-19 dashboard to help people navigate potential preprints to review

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/PREreview/rapid-prereview/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by rudietuesdays** [comment]
Tagged @georgiamoon and @murkatr to build wireframes for this!

**Comment by georgiamoon** [comment]
Here is a rough sketch of a tag dashboard idea:
![MVIMG_20200609_112323](https://user-images.githubusercontent.com/941210/84178633-b93c5300-aa52-11ea-8350-e50ef6cb01cf.jpg)

- The histogram would be a timeline of preprints + reviews
- The three blocks at the bottom would be "New Preprint Requests", "Review Activity" and "Reviewers"
- The about section could have some text about the tag/term/etc, or some other text that we could define, e.g. about the OASPA initiative

I think we'd want people to get to this view from the search for a term on the mainpage, or from a banner/ call to action on the homepage (something like that).

**Comment by georgiamoon** [comment]
@carijyao and I were meeting today to work on this, and we came up with some questions that we're trying to work through. The big one is what should be the "prioritized views" on the dashboard? In my initial sketch, I included the priorities that the OASPA team identified as important to that initiative:

- The histogram would be a timeline of preprints + reviews
- The three blocks at the bottom would be "New Preprint Requests", "Review Activity" and "Reviewers"
- The about section could have some text about the tag/term/etc, or some other text that we could define, e.g. about the OASPA initiative

In talking about it more today, we had a few questions and ideas! First we were focused on the path of wondering how to prioritize content for the various OASPA stakeholders, which we were thinking about how to answer: **what preprints should we give priority, sorted views to on the dashboard?**

- Preprints with the most reviews
- Preprints with the most requests
- Preprints that have been reviewed most recently
- Preprints that have been published most recently
- Preprints with the most activity
- Preprints with the least activity
   - e.g. Preprints from the last two weeks without any reviews
- Preprints with mostly "Yes" answers to "Should this preprint be submitted for publication"
- Preprints with mostly "Yes" to "Would you recommend this manuscript to others?"

Or — Should the dashboard focus on the stages of the review process? (to the extent that PREreview knows about that), e.g.

- PREprints that need review (Very few reviews, or lost of requests relative to reviews)
- Could be good for publication (i.e. use the answers the the questions, like mostly "Yes" answers to "Should this preprint be submitted for publication", mostly "Yes" to "Would you recommend this manuscript to others?")
- Potential Reviewers (Users who have been active or something like that?)

Curious for thoughts from @dasaderi @murkatr and @majohansson in particular!

**Comment by murkatr** [comment]
**From the 6/30 OASPA Preprint Working Group Call:**
- **Audience**: editors, publishers, and members of the OASPA Initiative
- **Purpose**: speed up the review process
- **Priorities to highlight**: 
- [ ] Most recommended (e.g. to others, for peer review, contains data)
- [ ] Most active reviewers (please don't lead with this)
- [ ] Link to recently requested preprints filtered on main page
- [ ] Link to recently reviewed preprints filtered on main page

**Comment by georgiamoon** [comment]
Thanks @murkatr ! That actually aligns pretty with the most recent sketch that @carijyao was working on so that's great!

One thing that we were realizing is that `recently requested` and `recently reviewed` could have the same preprint in their list, so we were thinking to have `recently requested, but NOT YET reviewed` as a distinction.

Does that seem right @dasaderi @murkatr ? 

@carijyao if you want to iterate on the sketch and share here — I think we have some good confirmation on the design direction!

**Comment by murkatr** [comment]
@georgiamoon @carijyao The OASPA group saw "most recommended" as a priority, so if we can adjust the sketch to make this the main/largest view with a "recent activity" list slightly smaller to the right of "most recommended", and a "active reviewer" list even smaller and off to the right side of the "recent activity". 

(1) most recommended - they were interested in seeing preprints listed that was recommended for:
- all three (to others, for peer review, contains data)
- to others/contains data
- for peer review/contains data 
- to others/without data
- for peer review/without data

(2) @dasaderi, feel free correct me if I'm wrong, but I think it would be more helpful to the editor/publisher audience to see recently requested AND recently reviewed in one list - initially, in my last comment, we were having users be redirected to the home page with the recently reviewed and recently requested filters on, HOWEVER, the one compiled list in the dashboard sounds great!

(3) most active reviewers

**Comment by carijyao** [comment]
![IMG_5476](https://user-images.githubusercontent.com/42358508/86321731-6cc9da80-bbee-11ea-8c75-cfb09149afba.jpg)

Let me know what you guys think! @georgiamoon @murkatr @dasaderi

**Comment by dasaderi** [comment]
@murkatr @georgiamoon and @carijyao thank you for all the thoughts and work so far.

I think what Katrina just wrote is correct. While I think there is value in building these dashboards from the perspective of a reviewer, I think here we should focus on the perspective of a reader/editor who needs to prioritize work for further review or for reading. So, having data/list of reviews filtered by the number of yeses to recommended for peer review and recommended to others with or without data, seems a priority.

**Comment by dasaderi** [comment]
Ooops, just refreshed and saw the new draft by @carijyao. I love it! So we ditched any visualization?

**Comment by carijyao** [comment]
What kind of visualization did you have in mind? And thanks for providing the prioritized user group. It's very helpful and I'll incorporate that into any future designs @dasaderi

**Comment by murkatr** [comment]
Awesome work @carijyao! The only thing I would add is that the Most Recommended also includes a drop-down option for both "recommended to others" AND "recommended for peer review".

RE: visualization - At first, @georgiamoon was envisioning a histogram of preprints and reviews, but when this idea was presented as an additional option (in a text list) to the OASPA Preprint WG they didn't seem to think that was a priority. 

We can certainly verify both of these points (and the new mockup) during Monday's OASPA Preprint WG meeting.

**Comment by murkatr** [comment]
@carijyao The OASPA Preprint Working Group loved your latest sketch. 

Since they were agreeing they'd like to see both recommended "to other" and "for peer review", we were thinking to have 4 checkboxes total: "Recommended to others", "Recommended for peer review", "Contains reported data", and "Contains reported code" or some other design that allows a combination of toggling the different options. Let me know if this doesn't make sense.

A visualization is not necessary right now. They thought numbers of preprints vs reviews can be loosely monitored for now and be considered as a future addition to the dashboard.

**Comment by rudietuesdays** [comment]
Should this issue be closed out @dasaderi @murkatr @georgiamoon ?

**Comment by murkatr** [comment]
Yes – thanks @rudietuesdays!
