### ISSUE TITLE
Add functionality to add tags to requests and make them searchable (e.g. COVID-19 tag)

### ISSUE THREAD

**Issue by dasaderi** [PREreview/rapid-prereview#83]

**Comment by dasaderi** [comment]
Tagging can help make the content more discoverable. Right now the user on OSrPRE has to tag the reviews with the "2019-nCOV" tag. Ideally we would have a system that searches for keywords in the title and abstract of the preprint to automatically tag or suggests tags of these preprints/reviews/requests.

**Comment by majohansson** [comment]
Reviews are categorized by diseases, not pathogens. So the tag should be "COVID-19" not 'SARS-CoV-2".

**Comment by dasaderi** [comment]
[Here](https://www.alia.org.au/groups/HLA/covid-19-live-literature-searches)'s a set of keywords we can use for querying the metadata.

**Comment by georgiamoon** [comment]
This is already in progress, but adding @dasaderi 's mockup of the disease tag list here

<img width="837" alt="Screen Shot 2020-06-01 at 3 21 49 PM" src="https://user-images.githubusercontent.com/941210/83445864-c5555e80-a41b-11ea-8b79-8551a4c92a7b.png">

**Comment by jheretic** [comment]
As per the decision to address this via linking disease tags to dynamic searches, this is fixed in #111
