### ISSUE TITLE
COVID-19 tag at the beginning of the tag list

### ISSUE THREAD

**Issue by dasaderi** [PREreview/rapid-prereview#96]
To better highlight COVID-19 content, it would be helpful to put SARS-CoV2 tag at the beginning of the tag list on the left and maybe bold it or highlight it somehow.

**Comment by majohansson** [comment]
Reviews are categorized by diseases, not pathogens. So the tag should be "COVID-19" not 'SARS-CoV-2".

**Comment by georgiamoon** [comment]
The main change I would make is to sort the tags on the side by number of preprints and not alphabetically, OR to add sort-ability there, but I think that'd be a bigger issue.

Based on @majohansson 's input, we should make it "COVID-19". I think right now it's actually nCoV19.

**Comment by dasaderi** [comment]
Thank you @majohansson. Made change here an on Issue #83
