### ISSUE TITLE
Update Beta Notice

### ISSUE THREAD

**Issue by dasaderi** [PREreview/rapid-prereview#99]
When should we remove the text that says that the platform is still a beta? 

**See updated comment below.**

**Comment by murkatr** [comment]
"Beta Notice: Please note that any reviews submitted during the beta stage of Outbreak Science Rapid PREreview may be lost in future updates."

We can change above to say, 
"Beta Notice: Please note that any reviews submitted during the beta stage of Outbreak Science Rapid PREreview will be migrated over into future updates."
